<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Regression III: categorical independent variables and multiple regression models | Modelling Criminological Data CRIM20452</title>
  <meta name="description" content="This is the course material for Modelling Criminological Data CRIM20452." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Regression III: categorical independent variables and multiple regression models | Modelling Criminological Data CRIM20452" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the course material for Modelling Criminological Data CRIM20452." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Regression III: categorical independent variables and multiple regression models | Modelling Criminological Data CRIM20452" />
  
  <meta name="twitter:description" content="This is the course material for Modelling Criminological Data CRIM20452." />
  

<meta name="author" content="" />


<meta name="date" content="2025-03-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regression-ii-numerical-independent-variables.html"/>
<link rel="next" href="categorical-variables-and-logistic-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelling Criminological Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A first lesson about R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-rstudio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#open-up-and-explore-rstudio"><i class="fa fa-check"></i><b>1.2</b> Open up and explore RStudio</a></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-the-rstudio-look"><i class="fa fa-check"></i><b>1.3</b> Customising the RStudio look</a></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#getting-organised-r-projects"><i class="fa fa-check"></i><b>1.4</b> Getting organised: R Projects</a></li>
<li class="chapter" data-level="1.5" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#functions-talk-to-your-computer"><i class="fa fa-check"></i><b>1.5</b> Functions: Talk to your computer</a></li>
<li class="chapter" data-level="1.6" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-packages"><i class="fa fa-check"></i><b>1.6</b> More on packages</a></li>
<li class="chapter" data-level="1.7" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#objects-creating-an-object"><i class="fa fa-check"></i><b>1.7</b> Objects: creating an object</a></li>
<li class="chapter" data-level="1.8" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#more-on-objects"><i class="fa fa-check"></i><b>1.8</b> More on objects</a></li>
<li class="chapter" data-level="1.9" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#naming-conventions-for-objects-in-r"><i class="fa fa-check"></i><b>1.9</b> Naming conventions for objects in R</a></li>
<li class="chapter" data-level="1.10" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#r-object-types-vectors"><i class="fa fa-check"></i><b>1.10</b> R object types: vectors</a></li>
<li class="chapter" data-level="1.11" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#r-object-types-data-frame"><i class="fa fa-check"></i><b>1.11</b> R object types: Data frame</a></li>
<li class="chapter" data-level="1.12" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#exploring-data"><i class="fa fa-check"></i><b>1.12</b> Exploring data</a></li>
<li class="chapter" data-level="1.13" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#r-data-types-factors"><i class="fa fa-check"></i><b>1.13</b> R data types: Factors</a></li>
<li class="chapter" data-level="1.14" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#how-to-import-data"><i class="fa fa-check"></i><b>1.14</b> How to import data</a></li>
<li class="chapter" data-level="1.15" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#how-to-use-comment"><i class="fa fa-check"></i><b>1.15</b> How to use ‘comment’</a></li>
<li class="chapter" data-level="1.16" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#how-to-quit-rstudio"><i class="fa fa-check"></i><b>1.16</b> How to Quit RStudio</a></li>
<li class="chapter" data-level="1.17" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#summary"><i class="fa fa-check"></i><b>1.17</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html"><i class="fa fa-check"></i><b>2</b> Getting to know your data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#causality-in-social-sciences"><i class="fa fa-check"></i><b>2.1</b> Causality in Social Sciences</a></li>
<li class="chapter" data-level="2.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#getting-data-thanks-to-reproducibility"><i class="fa fa-check"></i><b>2.2</b> Getting data thanks to reproducibility</a></li>
<li class="chapter" data-level="2.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#getting-a-sense-of-your-data"><i class="fa fa-check"></i><b>2.3</b> Getting a sense of your data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#first-steps"><i class="fa fa-check"></i><b>2.3.1</b> First steps</a></li>
<li class="chapter" data-level="2.3.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#on-tibbles-and-labelled-vectors"><i class="fa fa-check"></i><b>2.3.2</b> On tibbles and labelled vectors</a></li>
<li class="chapter" data-level="2.3.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#turning-variables-into-factors-and-changing-the-labels"><i class="fa fa-check"></i><b>2.3.3</b> Turning variables into factors and changing the labels</a></li>
<li class="chapter" data-level="2.3.4" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#looking-for-missing-data-and-other-anomalies"><i class="fa fa-check"></i><b>2.3.4</b> Looking for missing data and other anomalies</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>2.4</b> Data wrangling with dplyr</a></li>
<li class="chapter" data-level="2.5" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#using-dplyr-single-verbs"><i class="fa fa-check"></i><b>2.5</b> Using dplyr single verbs</a></li>
<li class="chapter" data-level="2.6" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#using-dplyr-for-grouped-operations"><i class="fa fa-check"></i><b>2.6</b> Using dplyr for grouped operations</a></li>
<li class="chapter" data-level="2.7" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#making-comparisons-with-numerical-outcomes"><i class="fa fa-check"></i><b>2.7</b> Making comparisons with numerical outcomes</a></li>
<li class="chapter" data-level="2.8" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#summary-1"><i class="fa fa-check"></i><b>2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html"><i class="fa fa-check"></i><b>3</b> Data visualisation with R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#anatomy-of-a-plot"><i class="fa fa-check"></i><b>3.2</b> Anatomy of a plot</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#what-graph-should-i-use"><i class="fa fa-check"></i><b>3.3</b> What graph should I use?</a></li>
<li class="chapter" data-level="3.4" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-histograms"><i class="fa fa-check"></i><b>3.4</b> Visualising numerical variables: Histograms</a></li>
<li class="chapter" data-level="3.5" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-density-plots"><i class="fa fa-check"></i><b>3.5</b> Visualising numerical variables: Density plots</a></li>
<li class="chapter" data-level="3.6" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#visualising-numerical-variables-box-plots"><i class="fa fa-check"></i><b>3.6</b> Visualising numerical variables: Box plots</a></li>
<li class="chapter" data-level="3.7" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#exploring-relationships-between-two-quantitative-variables-scatterplots"><i class="fa fa-check"></i><b>3.7</b> Exploring relationships between two quantitative variables: scatterplots</a></li>
<li class="chapter" data-level="3.8" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#scatterplots-conditioning-in-a-third-variable"><i class="fa fa-check"></i><b>3.8</b> Scatterplots conditioning in a third variable</a></li>
<li class="chapter" data-level="3.9" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#scatterplot-matrix"><i class="fa fa-check"></i><b>3.9</b> Scatterplot matrix</a></li>
<li class="chapter" data-level="3.10" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#titles-legends-and-themes-in-ggplot2"><i class="fa fa-check"></i><b>3.10</b> Titles, legends, and themes in ggplot2</a></li>
<li class="chapter" data-level="3.11" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#plotting-categorical-data-bar-charts"><i class="fa fa-check"></i><b>3.11</b> Plotting categorical data: bar charts</a></li>
<li class="chapter" data-level="3.12" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#further-resources"><i class="fa fa-check"></i><b>3.12</b> Further resources</a></li>
<li class="chapter" data-level="3.13" data-path="data-visualisation-with-r.html"><a href="data-visualisation-with-r.html#summary-2"><i class="fa fa-check"></i><b>3.13</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html"><i class="fa fa-check"></i><b>4</b> Refresher on descriptive statistics &amp; data carpentry</a>
<ul>
<li class="chapter" data-level="4.1" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#getting-some-data-from-eurobarometer"><i class="fa fa-check"></i><b>4.2</b> Getting some data from Eurobarometer</a></li>
<li class="chapter" data-level="4.3" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#thinking-about-your-data-filtering-cases"><i class="fa fa-check"></i><b>4.3</b> Thinking about your data: filtering cases</a></li>
<li class="chapter" data-level="4.4" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#selecting-variables-using-dplyrselect"><i class="fa fa-check"></i><b>4.4</b> Selecting variables: using <code>dplyr::select</code></a></li>
<li class="chapter" data-level="4.5" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#creating-summated-scales"><i class="fa fa-check"></i><b>4.5</b> Creating summated scales</a></li>
<li class="chapter" data-level="4.6" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#collapsing-categories-in-character-variables"><i class="fa fa-check"></i><b>4.6</b> Collapsing categories in character variables</a></li>
<li class="chapter" data-level="4.7" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#working-with-apparently-cryptic-variable-names-and-levels"><i class="fa fa-check"></i><b>4.7</b> Working with apparently cryptic variable names and levels</a></li>
<li class="chapter" data-level="4.8" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#recoding-factors"><i class="fa fa-check"></i><b>4.8</b> Recoding factors</a></li>
<li class="chapter" data-level="4.9" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#understanding-missing-data"><i class="fa fa-check"></i><b>4.9</b> Understanding missing data</a></li>
<li class="chapter" data-level="4.10" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#exploring-data-frames-visually"><i class="fa fa-check"></i><b>4.10</b> Exploring data frames visually</a></li>
<li class="chapter" data-level="4.11" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#a-quick-recap-on-descriptive-statistics"><i class="fa fa-check"></i><b>4.11</b> A quick recap on descriptive statistics</a>
<ul>
<li class="chapter" data-level="4.11.1" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#central-tendency"><i class="fa fa-check"></i><b>4.11.1</b> Central Tendency</a></li>
<li class="chapter" data-level="4.11.2" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#dispersion"><i class="fa fa-check"></i><b>4.11.2</b> Dispersion</a></li>
<li class="chapter" data-level="4.11.3" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#bivariate-analysis"><i class="fa fa-check"></i><b>4.11.3</b> Bivariate analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.12" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#further-resources-1"><i class="fa fa-check"></i><b>4.12</b> Further resources</a></li>
<li class="chapter" data-level="4.13" data-path="refresher-on-descriptive-statistics-data-carpentry.html"><a href="refresher-on-descriptive-statistics-data-carpentry.html#summary-3"><i class="fa fa-check"></i><b>4.13</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html"><i class="fa fa-check"></i><b>5</b> Regression I: Mean differences</a>
<ul>
<li class="chapter" data-level="5.1" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html#dependent-variable-numerical-independent-variable-binary"><i class="fa fa-check"></i><b>5.2</b> Dependent variable: numerical | Independent variable: binary</a></li>
<li class="chapter" data-level="5.3" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html#calculating-mean-differences-in-r"><i class="fa fa-check"></i><b>5.3</b> Calculating mean differences in <code>R</code></a></li>
<li class="chapter" data-level="5.4" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html#visual-exploration"><i class="fa fa-check"></i><b>5.4</b> Visual exploration</a></li>
<li class="chapter" data-level="5.5" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html#using-linear-regression-to-calculate-mean-differences"><i class="fa fa-check"></i><b>5.5</b> Using linear regression to calculate mean differences</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html#linear-regression"><i class="fa fa-check"></i><b>5.5.1</b> Linear Regression</a></li>
<li class="chapter" data-level="5.5.2" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html#linear-regression-as-a-difference-in-means-estimator"><i class="fa fa-check"></i><b>5.5.2</b> Linear Regression as a Difference-in-Means Estimator</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html#effect-size"><i class="fa fa-check"></i><b>5.6</b> Effect size</a></li>
<li class="chapter" data-level="5.7" data-path="regression-i-mean-differences.html"><a href="regression-i-mean-differences.html#lab-exercises"><i class="fa fa-check"></i><b>5.7</b> Lab Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="regression-ii-numerical-independent-variables.html"><a href="regression-ii-numerical-independent-variables.html"><i class="fa fa-check"></i><b>6</b> Regression II: numerical independent variables</a>
<ul>
<li class="chapter" data-level="6.1" data-path="regression-ii-numerical-independent-variables.html"><a href="regression-ii-numerical-independent-variables.html#introduction-3"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="regression-ii-numerical-independent-variables.html"><a href="regression-ii-numerical-independent-variables.html#motivating-regression"><i class="fa fa-check"></i><b>6.2</b> Motivating regression</a></li>
<li class="chapter" data-level="6.3" data-path="regression-ii-numerical-independent-variables.html"><a href="regression-ii-numerical-independent-variables.html#fitting-a-simple-regression-model"><i class="fa fa-check"></i><b>6.3</b> Fitting a simple regression model</a></li>
<li class="chapter" data-level="6.4" data-path="regression-ii-numerical-independent-variables.html"><a href="regression-ii-numerical-independent-variables.html#residuals-r-squared"><i class="fa fa-check"></i><b>6.4</b> Residuals: R squared</a></li>
<li class="chapter" data-level="6.5" data-path="regression-ii-numerical-independent-variables.html"><a href="regression-ii-numerical-independent-variables.html#is-this-the-same-as-last-week"><i class="fa fa-check"></i><b>6.5</b> Is this the same as last week?</a></li>
<li class="chapter" data-level="6.6" data-path="regression-ii-numerical-independent-variables.html"><a href="regression-ii-numerical-independent-variables.html#regression-assumptions"><i class="fa fa-check"></i><b>6.6</b> Regression assumptions</a></li>
<li class="chapter" data-level="6.7" data-path="regression-ii-numerical-independent-variables.html"><a href="regression-ii-numerical-independent-variables.html#lab-exercises-1"><i class="fa fa-check"></i><b>6.7</b> Lab Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression-iii-categorical-independent-variables-and-multiple-regression-models.html"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html"><i class="fa fa-check"></i><b>7</b> Regression III: categorical independent variables and multiple regression models</a>
<ul>
<li class="chapter" data-level="7.1" data-path="regression-iii-categorical-independent-variables-and-multiple-regression-models.html"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#fitting-regression-with-categorical-predictors"><i class="fa fa-check"></i><b>7.1</b> Fitting regression with categorical predictors</a></li>
<li class="chapter" data-level="7.2" data-path="regression-iii-categorical-independent-variables-and-multiple-regression-models.html"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#motivating-multiple-regression"><i class="fa fa-check"></i><b>7.2</b> Motivating multiple regression</a></li>
<li class="chapter" data-level="7.3" data-path="regression-iii-categorical-independent-variables-and-multiple-regression-models.html"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#fitting-and-interpreting-a-multiple-regression-model"><i class="fa fa-check"></i><b>7.3</b> Fitting and interpreting a multiple regression model</a></li>
<li class="chapter" data-level="7.4" data-path="regression-iii-categorical-independent-variables-and-multiple-regression-models.html"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#rescaling-input-variables-to-assist-interpretation"><i class="fa fa-check"></i><b>7.4</b> Rescaling input variables to assist interpretation</a></li>
<li class="chapter" data-level="7.5" data-path="regression-iii-categorical-independent-variables-and-multiple-regression-models.html"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#testing-conditional-hypothesis-interactions"><i class="fa fa-check"></i><b>7.5</b> Testing conditional hypothesis: interactions</a></li>
<li class="chapter" data-level="7.6" data-path="regression-iii-categorical-independent-variables-and-multiple-regression-models.html"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#multicollinearity"><i class="fa fa-check"></i><b>7.6</b> Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="categorical-variables-and-logistic-regression.html"><a href="categorical-variables-and-logistic-regression.html"><i class="fa fa-check"></i><b>8</b> Categorical variables and logistic regression</a>
<ul>
<li class="chapter" data-level="8.1" data-path="categorical-variables-and-logistic-regression.html"><a href="categorical-variables-and-logistic-regression.html#cross-tabulations"><i class="fa fa-check"></i><b>8.1</b> Cross-tabulations</a></li>
<li class="chapter" data-level="8.2" data-path="categorical-variables-and-logistic-regression.html"><a href="categorical-variables-and-logistic-regression.html#regression-modelling-why-not-linear-regression"><i class="fa fa-check"></i><b>8.2</b> Regression modelling: why not linear regression?</a></li>
<li class="chapter" data-level="8.3" data-path="categorical-variables-and-logistic-regression.html"><a href="categorical-variables-and-logistic-regression.html#logistic-regression"><i class="fa fa-check"></i><b>8.3</b> Logistic regression</a></li>
<li class="chapter" data-level="8.4" data-path="categorical-variables-and-logistic-regression.html"><a href="categorical-variables-and-logistic-regression.html#fitting-logistic-regression"><i class="fa fa-check"></i><b>8.4</b> Fitting logistic regression</a></li>
<li class="chapter" data-level="8.5" data-path="categorical-variables-and-logistic-regression.html"><a href="categorical-variables-and-logistic-regression.html#interactions"><i class="fa fa-check"></i><b>8.5</b> Interactions</a></li>
<li class="chapter" data-level="8.6" data-path="categorical-variables-and-logistic-regression.html"><a href="categorical-variables-and-logistic-regression.html#assessing-model-fit-confusion-matrix"><i class="fa fa-check"></i><b>8.6</b> Assessing model fit: confusion matrix</a></li>
<li class="chapter" data-level="8.7" data-path="categorical-variables-and-logistic-regression.html"><a href="categorical-variables-and-logistic-regression.html#lab-exercises-2"><i class="fa fa-check"></i><b>8.7</b> Lab Exercises</a></li>
<li class="chapter" data-level="8.8" data-path="categorical-variables-and-logistic-regression.html"><a href="categorical-variables-and-logistic-regression.html#further-resources-2"><i class="fa fa-check"></i><b>8.8</b> Further resources</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>9</b> Statistical Inference</a></li>
<li class="chapter" data-level="10" data-path="wrapping-up.html"><a href="wrapping-up.html"><i class="fa fa-check"></i><b>10</b> Wrapping up</a></li>
<li class="chapter" data-level="11" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>11</b> Appendix</a>
<ul>
<li class="chapter" data-level="11.0.1" data-path="appendix.html"><a href="appendix.html#expected-frequencies"><i class="fa fa-check"></i><b>11.0.1</b> Expected frequencies</a></li>
<li class="chapter" data-level="11.1" data-path="appendix.html"><a href="appendix.html#logistic-regression-1"><i class="fa fa-check"></i><b>11.1</b> Logistic regression</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="appendix.html"><a href="appendix.html#fitting-logistic-regression-alternative"><i class="fa fa-check"></i><b>11.1.1</b> Fitting logistic regression: alternative</a></li>
<li class="chapter" data-level="11.1.2" data-path="appendix.html"><a href="appendix.html#assessing-model-fit-deviance-and-pseudo-r-squared"><i class="fa fa-check"></i><b>11.1.2</b> Assessing model fit: deviance and pseudo r squared</a></li>
<li class="chapter" data-level="11.1.3" data-path="appendix.html"><a href="appendix.html#assessing-model-fit-roc-curves"><i class="fa fa-check"></i><b>11.1.3</b> Assessing model fit: ROC curves</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Modelling Criminological Data CRIM20452</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression-iii-categorical-independent-variables-and-multiple-regression-models" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Regression III: categorical independent variables and multiple regression models<a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#regression-iii-categorical-independent-variables-and-multiple-regression-models" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In previous weeks, we learned that linear regression models are a powerful method that allows us to assess the association between a binary or numerical independent variable and a numerical dependent variable. This week, we will develop these models even further. Specifically, we will learn how to handle scenarios when the dependent variable is numerical (as in previous weeks), but the independent variable is categorical with more than two groups (i.e., ordinal or nominal variables). In addition, we will finally introduce the world of <em>multivariate analysis</em>, when we analyse more than two variables at the same time.</p>
<div id="fitting-regression-with-categorical-predictors" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Fitting regression with categorical predictors<a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#fitting-regression-with-categorical-predictors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>With linear regression models, the dependent variable <span class="math inline">\(Y\)</span> will always be numerical. If the independent variable <span class="math inline">\(X\)</span> is numerical, the estimated slope coefficient <span class="math inline">\(\beta\)</span> implies that every one-unit increase in <span class="math inline">\(X\)</span> is associated with a <span class="math inline">\(\beta\)</span>-increase in <span class="math inline">\(Y\)</span>. If the independent variable <span class="math inline">\(X\)</span> is binary, the estimated slope coefficient <span class="math inline">\(\beta\)</span> implies the mean difference: expected scores of <span class="math inline">\(Y\)</span> in the comparison group are <span class="math inline">\(\beta\)</span> units higher/lower than in the reference group. Now, let’s expand that rationale to other categorical independent variables with more than two groups. It is quite straightforward to run it, and very similar to the binary case!</p>
<p>We will use the same dataset from last week. We will use the replication data from one of the papers that Prof Sharkey published to study what contributed to the decline of crime from the 1990s. This data is found in the <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/46WIH0">Harvard Dataverse</a>. If you are interested in the specific study analysing this data, you can find it <a href="https://journals.sagepub.com/doi/abs/10.1177/0003122417736289">here</a>.</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb433-1" tabindex="-1"></a><span class="co"># create an object with the URL address of the dataset</span></span>
<span id="cb433-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb433-2" tabindex="-1"></a>urlfile <span class="ot">&lt;-</span> <span class="st">&quot;https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/46WIH0/ARS2VS&quot;</span></span>
<span id="cb433-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb433-3" tabindex="-1"></a></span>
<span id="cb433-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb433-4" tabindex="-1"></a><span class="co"># import the dataset into R</span></span>
<span id="cb433-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb433-5" tabindex="-1"></a>communitycrime <span class="ot">&lt;-</span> <span class="fu">read.table</span>(urlfile, <span class="at">sep =</span> <span class="st">&#39;</span><span class="sc">\t</span><span class="st">&#39;</span>,<span class="at">header =</span> T)</span></code></pre></div>
<p>As before, we create an object with the permanent <code>URL</code> address, and then we use a function to read the data into <code>R</code>. We use the <code>read.table()</code> function from base <code>R</code> for this. We pass two arguments to the function <code>sep= '\t'</code>, telling <code>R</code> this file is tab separated. The <code>header = T</code> function tells <code>R</code> that it is <code>TRUE</code> (<code>T</code>) that this file has a first row that acts as a header (this row has the name of the variables).</p>
<p>There are many more variables here than we will need, so let’s do some filtering and selection. We will focus on 2012, the most recent year in the dataset, and just a few select variables.</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb434-1" tabindex="-1"></a><span class="co"># load the dplyr package for data cleaning</span></span>
<span id="cb434-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb434-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 4.3.3</code></pre>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb436-1" tabindex="-1"></a><span class="co"># create a new object, &#39;df&#39;, that only includes observations from 2012</span></span>
<span id="cb436-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb436-2" tabindex="-1"></a><span class="co"># and removes missing observations from the variable &#39;region&#39;</span></span>
<span id="cb436-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb436-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">filter</span>(communitycrime, year <span class="sc">==</span> <span class="st">&quot;2012&quot;</span>, <span class="sc">!</span><span class="fu">is.na</span>(region))</span>
<span id="cb436-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb436-4" tabindex="-1"></a></span>
<span id="cb436-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb436-5" tabindex="-1"></a><span class="co"># select just some variables from the dataset</span></span>
<span id="cb436-6"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb436-6" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">select</span>(df, place_name, state_name, region, viol_r, black, lesshs, unemployed, fborn, incarceration, log_incarceraton, swornftime_r, log_viol_r, largest50)</span></code></pre></div>
<p>So now we have a more manageable data set that we can use for this session. Our unit of analysis, as last week, are cities in the United States, and our sample includes 263 US cities (see <code>place_name</code>) across 44 states. See previous weeks for the code on how to figure out what these states are.</p>
<p>We have one categorical variable with more than two groups in this dataset, <code>region</code>, which identifies the region in the United States the city is located in. There are four regions: East Coast, Midwest, South, and West Coast. Let’s start recoding this variable to ensure that it is treated as a factor with the relevant labels.</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb437-1" tabindex="-1"></a><span class="co"># frequency table of the variable &#39;region&#39;</span></span>
<span id="cb437-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb437-2" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>region)</span></code></pre></div>
<pre><code>## 
##   1   2   3   4 
##  23  45  91 104</code></pre>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb439-1" tabindex="-1"></a><span class="co"># factorising variable &#39;region&#39; and assigning relevant labels</span></span>
<span id="cb439-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb439-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">region =</span> <span class="fu">factor</span>(region, </span>
<span id="cb439-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb439-3" tabindex="-1"></a>                                 <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>), </span>
<span id="cb439-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb439-4" tabindex="-1"></a>                                 <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;East Coast&quot;</span>, <span class="st">&quot;Midwest&quot;</span>, <span class="st">&quot;South&quot;</span>, <span class="st">&quot;West Coast&quot;</span>)))</span>
<span id="cb439-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb439-5" tabindex="-1"></a></span>
<span id="cb439-6"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb439-6" tabindex="-1"></a><span class="co"># frequency table of variable &#39;region&#39; to make sure</span></span>
<span id="cb439-7"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb439-7" tabindex="-1"></a><span class="co"># that our changes worked as expected</span></span>
<span id="cb439-8"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb439-8" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>region)</span></code></pre></div>
<pre><code>## 
## East Coast    Midwest      South West Coast 
##         23         45         91        104</code></pre>
<p>One possible avenue for research here is exploring the extent to which different regions in the US have different rates of violence. In this case, as in previous weeks, violence rate would be our dependent variable and region in the US, our independent variable. The question, then, is whether we can simply throw a categorical independent variable in a regression model.</p>
<p>Now, let’s return to Week 5 for a minute and remember how we handle <em>binary</em> independent variables. If our independent variable is binary, what we want to do is essentially calculate the mean of the dependent variable across both groups of the independent variable. With a categorical (ordinal or nominal) variable, we can start similarly: we can start calculating the mean of the dependent variable across <em>all</em> groups of the independent variable. For example, let’s calculate the average rate of violence across the four regions in the US.</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb441-1" tabindex="-1"></a><span class="co"># calculate the mean of &#39;viol_r&#39; across groups of &#39;region&#39;</span></span>
<span id="cb441-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb441-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb441-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb441-3" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span></span>
<span id="cb441-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb441-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">average =</span> <span class="fu">mean</span>(viol_r))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 2
##   region     average
##   &lt;fct&gt;        &lt;dbl&gt;
## 1 East Coast    790.
## 2 Midwest       634.
## 3 South         589.
## 4 West Coast    417.</code></pre>
<p>Great, we know that the average violence rate in cities in the East Coast is 790, the average violence rate in cities in the Midwest is 634, the average violence rate in cities in the South is 589, and the average violence rate in cities in the West Coast is 417. We can also visually inspect those mean differences using a grouped boxplot.</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb443-1" tabindex="-1"></a><span class="co"># load the &#39;ggplot2&#39; package</span></span>
<span id="cb443-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb443-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.3.2</code></pre>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb445-1" tabindex="-1"></a><span class="co"># produce a grouped boxplot assessing the distribution of</span></span>
<span id="cb445-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb445-2" tabindex="-1"></a><span class="co"># &#39;viol_r&#39; across groups of &#39;region&#39;</span></span>
<span id="cb445-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb445-3" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x =</span> region, <span class="at">y =</span> viol_r)) <span class="sc">+</span></span>
<span id="cb445-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb445-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="07_regression_III_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Now, how about including this categorical variable as an independent variable in a regression model? If we think about it, theoretically, we could recode this categorical variable into several binary variables. For example, we could create one binary variable that indicates whether the city is from the East Coast (<span class="math inline">\(=1\)</span>) or elsewhere (<span class="math inline">\(=0\)</span>), another binary variable indicating whether the city is from the Midwest (<span class="math inline">\(=1\)</span>) or elsewhere (<span class="math inline">\(=0\)</span>), another binary variable indicating whether the city is from the South (<span class="math inline">\(=1\)</span>) or elsewhere (<span class="math inline">\(=0\)</span>), and a fourth binary variable indicating whether the city is from the West Coast (<span class="math inline">\(=1\)</span>) or elsewhere (<span class="math inline">\(=0\)</span>). This would be good because we already know how to handle binary independent variables. Given that the variable <code>region</code> has four groups, we could create four new binary variables.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-1" tabindex="-1"></a><span class="co"># create four new binary variables based on groups of &#39;region&#39;</span></span>
<span id="cb446-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df,</span>
<span id="cb446-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-3" tabindex="-1"></a>             <span class="at">east_coast =</span> <span class="fu">case_when</span>(region <span class="sc">==</span> <span class="st">&quot;East Coast&quot;</span> <span class="sc">~</span> <span class="dv">1</span>, <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>),</span>
<span id="cb446-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-4" tabindex="-1"></a>             <span class="at">midwest =</span> <span class="fu">case_when</span>(region <span class="sc">==</span> <span class="st">&quot;Midwest&quot;</span> <span class="sc">~</span> <span class="dv">1</span>, <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>),</span>
<span id="cb446-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-5" tabindex="-1"></a>             <span class="at">south =</span> <span class="fu">case_when</span>(region <span class="sc">==</span> <span class="st">&quot;South&quot;</span> <span class="sc">~</span> <span class="dv">1</span>, <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>),</span>
<span id="cb446-6"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-6" tabindex="-1"></a>             <span class="at">west_coast =</span> <span class="fu">case_when</span>(region <span class="sc">==</span> <span class="st">&quot;West Coast&quot;</span> <span class="sc">~</span> <span class="dv">1</span>, <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>)</span>
<span id="cb446-7"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-7" tabindex="-1"></a>             )</span>
<span id="cb446-8"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-8" tabindex="-1"></a></span>
<span id="cb446-9"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-9" tabindex="-1"></a><span class="do">## Now, let&#39;s check if this worked</span></span>
<span id="cb446-10"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-10" tabindex="-1"></a></span>
<span id="cb446-11"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-11" tabindex="-1"></a><span class="co"># table of frequency for new binary variable &#39;east_coast&#39;</span></span>
<span id="cb446-12"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb446-12" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>east_coast)</span></code></pre></div>
<pre><code>## 
##   0   1 
## 240  23</code></pre>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb448-1" tabindex="-1"></a><span class="co"># table of frequency for new binary variable &#39;midwest&#39;</span></span>
<span id="cb448-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb448-2" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>midwest)</span></code></pre></div>
<pre><code>## 
##   0   1 
## 218  45</code></pre>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb450-1" tabindex="-1"></a><span class="co"># table of frequency for new binary variable &#39;south&#39;</span></span>
<span id="cb450-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb450-2" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>south)</span></code></pre></div>
<pre><code>## 
##   0   1 
## 172  91</code></pre>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb452-1" tabindex="-1"></a><span class="co"># table of frequency for new binary variable &#39;west_coast&#39;</span></span>
<span id="cb452-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb452-2" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>west_coast)</span></code></pre></div>
<pre><code>## 
##   0   1 
## 159 104</code></pre>
<p>Great, it worked! Now, each one of the groups is presented by its own binary variable. We could, for example, simply estimate four separate regression models, each including one independent binary variable. That would allow us to examine the association between region and rates of violence!</p>
<p>True, that would… but that’s not very efficient. After all, we had to manually create four separate binary variables and then would need to run four separate linear regression models. Not exactly an easy solution.</p>
<p>Now, let’s think again — a bit more deeply — about what the regression model estimates when we have a binary independent variable. Let’s use the variable <code>largest50</code> as a quick example — this variable indicates whether the city is one of the 50 largest cities in the US. As we know, a linear model is given by</p>
<p><span class="math display">\[
Y = \alpha + \beta \cdot X
\]</span>
If we regress rates of violence (<code>viol_r</code>) on this binary indicator (<code>largest50</code>), the regression estimator will yield estimates of the intercept (<span class="math inline">\(\alpha\)</span>) and the slope coefficient (<span class="math inline">\(\beta\)</span>).</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb454-1" tabindex="-1"></a><span class="co"># fit a regression model with &#39;viol_r&#39; as the DV and &#39;largest50&#39; as the IV</span></span>
<span id="cb454-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb454-2" tabindex="-1"></a><span class="fu">lm</span>(viol_r <span class="sc">~</span> largest50, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = viol_r ~ largest50, data = df)
## 
## Coefficients:
## (Intercept)    largest50  
##       484.4        339.2</code></pre>
<p>Based on the output above, we know that the estimated intercept is <span class="math inline">\(\widehat{\alpha}=484.4\)</span>, indicating the average rates of violence in smaller cities. We also know that the estimated slope coefficient is <span class="math inline">\(\widehat{\beta}=339.2\)</span>, indicating that the average rate of violence is 339.2 scores higher in the larger cities than in smaller cities.</p>
<p>In other words, we had a categorical variable with two groups (<code>largest50</code><span class="math inline">\(=0\)</span> indicating smaller cities and <code>largest50</code><span class="math inline">\(=1\)</span> indicating larger cities), we estimated a regression model, which then returned the average score for one of the groups (<span class="math inline">\(\alpha\)</span>, for the <em>reference group</em>) and one slope coefficient indicating the mean difference between that group and the reference group (<span class="math inline">\(\beta\)</span>).</p>
<p>Now, let’s fit another regression model where the dependent variable is rates of violence (<code>viol_r</code>) and the independent variable is region (<code>region</code>), a categorical variable. Let’s see what happens.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb456-1" tabindex="-1"></a><span class="co"># fit a regression model with &#39;viol_r&#39; as the DV and &#39;region&#39; as the IV</span></span>
<span id="cb456-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb456-2" tabindex="-1"></a><span class="fu">lm</span>(viol_r <span class="sc">~</span> region, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = viol_r ~ region, data = df)
## 
## Coefficients:
##      (Intercept)     regionMidwest       regionSouth  regionWest Coast  
##            790.0            -155.6            -200.9            -373.2</code></pre>
<p>It works! But how do we make sense of it? We now have one estimated intercept and <strong>three</strong> estimated slope coefficients! The estimated intercept (<span class="math inline">\(\widehat{\alpha}=790\)</span>) we immediately recognise as the mean rate of violence in the East Coast (check the grouped averages above!). And the three slope coefficients all make reference to the remaining groups: Midwest (<span class="math inline">\(\widehat{\beta}=-155.6\)</span>), South (<span class="math inline">\(\widehat{\beta}=-200.9\)</span>), and West Coast (<span class="math inline">\(\widehat{\beta}=-373.2\)</span>). What’s going on here?</p>
<p>Essentially, what happened is that we have four different groups. One of those groups is what we call the <strong>reference category</strong>: this is the group whose average is represented by the Intercept. Then, the model returns one coefficient for each of the remaining groups. Those coefficients reflect the mean difference between each group and the reference group. For example, the slope coefficient for the Midwest is <span class="math inline">\(\widehat{\beta}=-155.6\)</span>, implying that cities in the Midwest have an average rate of violence 155.6 units lower than the average rate of violence in the East Coast. This checks out! We knew that the average violence rate in Midwest cities was 634, which is exactly 156 units lower than the East Coast’s average of 790 (any small differences are due to rounding error).</p>
<p>Similarly, the slope coefficient for the South is <span class="math inline">\(\widehat{\beta}=-200.9\)</span>, implying that cities in the South have an average rate of violence 200.9 units lower than the average rate of violence in the East Coast. the slope coefficient for- the West Coast is <span class="math inline">\(\widehat{\beta}=-373.2\)</span>, implying that cities in the West Coast have an average rate of violence 200.9 units lower than the average rate of violence in the East Coast.</p>
<p>With categorical variables, the value of the intercept is the mean value of <span class="math inline">\(Y\)</span> in the <strong>reference category</strong>, and then we have one slope coefficient for each of the remaining groups—each one of them indicating the estimated mean difference between that group and the reference group. If, hypothetically, we had a categorical variable with 10 groups and used it as an independent variable in a regression model, that would yield nine slope coefficients—each one of them estimating the mean difference between each group and reference category.</p>
<p>Now, before we created a series of binary variables. What if we used them instead of the <code>region</code> variable? For example, we could fit a regression model including the binary variables <code>midwest</code>, <code>south</code>, and <code>west_coast</code> as independent variables at the same time.</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb458-1" tabindex="-1"></a><span class="co"># fit a regression model with binary independent variables</span></span>
<span id="cb458-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb458-2" tabindex="-1"></a><span class="fu">lm</span>(viol_r <span class="sc">~</span> midwest <span class="sc">+</span> south <span class="sc">+</span> west_coast, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = viol_r ~ midwest + south + west_coast, data = df)
## 
## Coefficients:
## (Intercept)      midwest        south   west_coast  
##       790.0       -155.6       -200.9       -373.2</code></pre>
<p>It’s exactly the same model! That’s what <code>R</code> is doing in the background. Because we left the group ‘East Coast’ out, we are treating it as the reference category. Therefore, its average score is represented by the estimated intercept. Then, each slope coefficient estimates the mean difference between each group and the reference group. What <code>R</code> is doing in the background is exactly that: creating a bunch of binary variables from the categorical variable, including each one of them as a separate variable in the model—except for one group, which is left out and treated as the reference category, so that all comparisons are made against this group.</p>
<p>So, that’s great! We don’t need to manually create a bunch of new binary variables. Every time we include a <code>factor</code> as an independent variable, <code>R</code> will do all of that automatically for us. We just need to make sure we interpret the coefficients correctly! It’s as if we were estimating the following linear model:</p>
<p><span class="math display">\[
viol\_r = \alpha + \beta_1\cdot MidWest + \beta_2\cdot South + \beta_3\cdot West Coast
\]</span></p>
<p>When dealing with categorical independent variables, therefore, a key question becomes the choice of the reference category. We need to choose the reference category that makes more sense for us, given that all comparisons will be made against that group. We can check which group is the reference category by checking the <code>levels()</code> of the factor variable; <code>R</code> will always pick the first category as the reference category.</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb460-1" tabindex="-1"></a><span class="co"># checking the levels of variable &#39;region&#39;</span></span>
<span id="cb460-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb460-2" tabindex="-1"></a><span class="fu">levels</span>(df<span class="sc">$</span>region)</span></code></pre></div>
<pre><code>## [1] &quot;East Coast&quot; &quot;Midwest&quot;    &quot;South&quot;      &quot;West Coast&quot;</code></pre>
<p>Because the group “East Coast” is the first group, <code>R</code> has picked it as the reference category in the regression model above. If we want to change the reference category, we can use the <code>fct_relevel()</code> function from the <code>forcats</code> package. For example, if we want the West Coast to be the reference group, we simply use the following code:</p>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-1" tabindex="-1"></a><span class="co"># install the package if you haven&#39;t yet. You only need to do it once.</span></span>
<span id="cb462-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-2" tabindex="-1"></a><span class="do">## install.packages(&quot;forcats&quot;)</span></span>
<span id="cb462-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-3" tabindex="-1"></a></span>
<span id="cb462-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-4" tabindex="-1"></a><span class="co"># load the &#39;forcats&#39; package</span></span>
<span id="cb462-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-5" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb462-6"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-6" tabindex="-1"></a></span>
<span id="cb462-7"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-7" tabindex="-1"></a><span class="co"># changing the reference group of variable &#39;region&#39; to West Coast</span></span>
<span id="cb462-8"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-8" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(df, <span class="at">region =</span> <span class="fu">fct_relevel</span>(region, <span class="st">&quot;West Coast&quot;</span>))</span>
<span id="cb462-9"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-9" tabindex="-1"></a></span>
<span id="cb462-10"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-10" tabindex="-1"></a><span class="co"># check that it worked. &#39;West Coast&#39; should be the first group now</span></span>
<span id="cb462-11"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb462-11" tabindex="-1"></a><span class="fu">levels</span>(df<span class="sc">$</span>region)</span></code></pre></div>
<pre><code>## [1] &quot;West Coast&quot; &quot;East Coast&quot; &quot;Midwest&quot;    &quot;South&quot;</code></pre>
<p>If we estimate a regression model with <code>viol_r</code> as the dependent variable and <code>region</code> as the independent variable, we will get different results now.</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb464-1" tabindex="-1"></a><span class="co"># regression model using &#39;West Coast&#39; as the reference group</span></span>
<span id="cb464-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb464-2" tabindex="-1"></a><span class="fu">lm</span>(viol_r <span class="sc">~</span> region, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = viol_r ~ region, data = df)
## 
## Coefficients:
##      (Intercept)  regionEast Coast     regionMidwest       regionSouth  
##            416.8             373.2             217.6             172.4</code></pre>
<p><strong>Important!</strong> The code we used to fit this regression model is <em>exactly</em> the same as before. Yet, the results are different. Now, we are treating ‘West Coast’ as the reference group. Therefore, the estimated intercept <span class="math inline">\(\widehat{\alpha}=416.8\)</span> is the average violence rate in the West Coast, and each of the three slope coefficients is the difference between the average violence rates in each region and in the West Coast.</p>
<p>Always check what is the reference category when dealing with categorical independent variables!</p>
</div>
<div id="motivating-multiple-regression" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Motivating multiple regression<a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#motivating-multiple-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Hang on! In the model above, we estimated not only <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span>, but actually <span class="math inline">\(\alpha, \beta_1, \beta_2,\)</span> and <span class="math inline">\(\beta_3\)</span>! How come we estimated so many regression coefficients? Welcome to <strong>multiple regression models</strong>, our first stop in multivariate analysis!</p>
<p>Say you have a dataset from a given hypothetical city. This dataset contains 365 rows, one for each day of the year. One of the columns included in this dataset is a count of robberies that were recorded by the police each day. Another column indicates how many ice creams were sold that day. Just for fun, you decide to estimate a regression model where robbery counts is the dependent variable and ice cream sales is the independent variable. Interestingly, you find a positive and strong association! Every additional ice cream sold was associated with an expected increase in robberies! You check model assumptions and model fit, and it all seems fine. What’s going on here? Should we ban ice creams as a criminal policy aiming to reduce robberies?</p>
<p>We shouldn’t, of course. The association between ice cream consumption and robberies is a <em>spurious association</em>.^ [You must have heard before that correlation does not equal causation. Just because two things are associated, we cannot assume that one is the cause of the other. Typically, we see how the pilots switch on the secure belt button when there is turbulence. These two things are associated - they tend to come together. But the pilots are not causing the turbulences by pressing a switch! The world is full of <strong>spurious correlations</strong>, associations between two variables that should not be taken too seriously. You can explore a few <a href="http://tylervigen.com/">here</a>. It’s funny.] In this case, what we have is a common factor not accounted for: weather. On hot, sunny days, people consume more ice creams; and on hot, sunny days, with more people circulating on the streets, more crimes tend to happen. Therefore, what we have here is a bivariate association between ice cream consumption and robberies generated by a third common factor. By not accounting for weather, we find a non-causal association induced by a <em>confounder</em>. That’s not good! Our result indicating a positive association between ice cream consumption and robberies is actually biased—once weather is accounted for, there is no association!</p>
<p>It’s always important to think about potential confounders—i.e., potential third common factors not accounted for. Every time we examine the association between an independent variable <span class="math inline">\(X\)</span> and a dependent variable <span class="math inline">\(Y\)</span>, we need to ask ourselves: could there be a third common factor causing both <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>? If there is, our regression model could be biased since not accounting for that confounder could potentially lead to a spurious association.</p>
<p>Looking only at covariation between pairs of variables can be misleading. It may lead you to conclude that a relationship is more important than it really is. This is no trivial matter, but one of the most important ones we confront in research and policy.</p>
<p>It’s not an exaggeration to say that most quantitative explanatory research is about trying to control for the presence of <strong>confounders</strong>, variables that may explain away observed associations. Think about any criminology question: Does marriage reduce crime? Or is it that people who get married are different from those who don’t (and are those pre-existing differences that are associated with less crime)? Do gangs lead to more crime? Or is it that young people who join gangs are more likely to be offenders to start with? Are the police being racist when they stop and search more members of ethnic minorities? Or are there other factors (i.e., offending, area of residence, time spent in the street) that, once controlled, would mean no ethnic disproportionality in stop and searches? Does a particular program reduce crime? Or is the observed change due to something else?</p>
<p>These things also matter for policy. Wilson and Kelling, for example, argued that signs of incivility (or antisocial behaviour) in a community lead to more serious forms of crime later on as people withdraw to the safety of their homes when they see those signs of incivilities, and this leads to a reduction in informal mechanisms of social control. All the policies to tackle antisocial behaviour in this country are very much informed by this model and were heavily influenced by the broken windows theory.</p>
<p>But is the model right? Sampson and Raudenbush argue that this is not entirely correct. They argued and tried to show that other confounding (poverty, collective efficacy) factors explain the association between signs of incivility and more serious crime. In other words, the reason why you see antisocial behaviour in the same communities that you see crime is because other structural factors explain both of those outcomes. They also argue that perceptions of antisocial behaviour are not just produced by observed antisocial behaviour but also by stereotypes about social class and race. If you believe them, then the policy implications are that only tackling antisocial behaviour won’t help you to reduce crime (as Wilson and Kelling have argued). So, as you can see, this stuff matters for policy, not just for theory.</p>
<p>That’s when <strong>multiple regression models</strong> become super useful! Multiple regression is one way of checking the relevance of competing explanations. You could set up a model where you try to predict crime levels with an indicator of broken windows and an indicator of structural disadvantage. If, after controlling for structural disadvantage, you see that the regression coefficient for broken windows is still significant, you may be onto something, particularly if the estimated effect is still large. If, on the other hand, the regression coefficient of your broken windows variable is no longer significant, then you may be tempted to think that perhaps Sampson and Raudenbush were onto something.</p>
</div>
<div id="fitting-and-interpreting-a-multiple-regression-model" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Fitting and interpreting a multiple regression model<a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#fitting-and-interpreting-a-multiple-regression-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>It could not be any easier to fit a multiple regression model. The linear model simply includes more coefficients:</p>
<p><span class="math display">\[
Y = \alpha + \beta_1\cdot X_1 + \beta_2\cdot X_2 + \beta_3\cdot X_3 + ... + \beta_n\cdot X_n
\]</span></p>
<p>In other words, we still have only one dependent variable <span class="math inline">\(Y\)</span>, which has to be numerical. We also have several independent variables <span class="math inline">\(X_1, X_2, X_3, ..., X_n\)</span>, and for each independent variable, we have an associated slope coefficient <span class="math inline">\(\beta_1, \beta_2, \beta_3, ..., \beta_n\)</span>.</p>
<p>To estimate a multiple regression in <code>R</code>, you simply modify the formula in the <code>lm()</code> function by adding terms for the additional inputs. The model works like this:</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb466-1" tabindex="-1"></a><span class="co"># multiple regression formula: we just add as many independent variables as we need</span></span>
<span id="cb466-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb466-2" tabindex="-1"></a><span class="fu">lm</span>(dependent_variable <span class="sc">~</span> independent_variable_1 <span class="sc">+</span> independent_variable_2 <span class="sc">+</span> independent_variable_3 <span class="sc">+</span> independent_variable_4, <span class="at">data =</span> dataset )</span></code></pre></div>
<p>For example, let’s regress violence rates on unemployment percentage in a city and whether the city is one of the 50 largest cities in the country. This linear model would look like this:</p>
<p><span class="math display">\[
viol\_r = \alpha + \beta_1\cdot unemployed + \beta_2\cdot largest50
\]</span></p>
<p>So, now have three regression coefficients to estimate: <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\beta_2\)</span>. We can use the <code>lm()</code> function in <code>R</code> to estimate them.</p>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb467-1" tabindex="-1"></a><span class="co"># fit multiple regression model</span></span>
<span id="cb467-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb467-2" tabindex="-1"></a>multiple_regression <span class="ot">&lt;-</span> <span class="fu">lm</span>(viol_r <span class="sc">~</span> unemployed <span class="sc">+</span> largest50, <span class="at">data=</span>df)</span>
<span id="cb467-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb467-3" tabindex="-1"></a></span>
<span id="cb467-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb467-4" tabindex="-1"></a><span class="co"># print results of the multiple regression model</span></span>
<span id="cb467-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb467-5" tabindex="-1"></a>multiple_regression</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = viol_r ~ unemployed + largest50, data = df)
## 
## Coefficients:
## (Intercept)   unemployed    largest50  
##      -236.3        116.5        295.5</code></pre>
<p>What do the two coefficients mean now? <strong>Their interpretation now changes</strong>!</p>
<p>The intercept is the expected score of <span class="math inline">\(Y\)</span> when <em>all</em> independent variables are 0. In this case, the intercept is the expected violence rate when both <span class="math inline">\(unemployed = 0\)</span> and <span class="math inline">\(largest50 = 0\)</span>. That is, a hypothetical city with 0% of its population unemployed and that is not one of the 50 largest cities in the country is expected to have a violence rate of <span class="math inline">\(=236.3\)</span>. From now on, more often than not, there is not much value in bothering to interpret the intercept because it will not always represent a real observation in your sample.</p>
<p>The slope coefficients represent the <em>partial association</em> between the independent variable and dependent variable <em>controlling for the other independent variables</em>. In this case, the coefficient <span class="math inline">\(\widehat{\beta_1}=116.5\)</span> implies that, <em>controlling for whether or not the city is one of the largest 50 cities in the country</em>, every additional percentage point increase in unemployment is associated with an expected increase of 116.5 in violence rates. Similarly, the coefficient <span class="math inline">\(\widehat{\beta_2}=295.5\)</span> implies that, <em>controlling for unemployment percentage</em>, cities in the top 50 by size have an expected violence rate 295.5 units higher than smaller cities.</p>
<p>Other interpretations are also possible and are more generalizable. Gelman and Hill (2007: p. 34) emphasise what they call the <em>predictive interpretation</em> which considers how “the outcome variable differs, on average, when comparing two groups of units that differ by 1 in the relevant predictor while being identical in all the other predictors”. So <a href="http://andrewgelman.com/2013/01/05/understanding-regression-models-and-regression-coefficients/">if you’re regressing y on u and v, the coefficient of u is the average difference in y per difference in u, comparing pairs of items that differ in u but are identical in v</a>.</p>
<p>So, for example, in this case, we could say that comparing respondents who have the same level of unemployment but who differ in whether they are one of the largest cities or not, the model predicts an expected difference of 295.5 in their violent crime measure. And cities with the same size category but that differ by 1% point in unemployment, we would expect to see a difference of 116.5 in their violent crime measure. So, we are interpreting the regression slopes <strong>as comparisons of observation that differ in one predictor while being at the same levels of the other predictors</strong>.</p>
<p>As you can see, interpreting regression coefficients can be kind of tricky<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a>. The relationship between the dependent variable <span class="math inline">\(Y\)</span> and any one explanatory variable can change greatly depending on what other explanatory variables are present in the model.</p>
<p>Something you need to be particularly careful about is to interpret the coefficients in a causal manner. Unless your data comes from an experiment, this is unlikely to be helpful. With observational data, regression coefficients should not be read as indexing causal relations. This sort of textbook warning is, however, often neglectfully ignored by professional researchers. Often, authors carefully draw sharp distinctions between causal and correlational claims when discussing their data analysis but then interpret the correlational patterns in a totally causal way in their conclusion section. This is what is called the <a href="http://junkcharts.typepad.com/numbersruleyourworld/2012/07/the-causation-creep.html">causation</a> creep. Beware. Don’t do this tempting as it may be.</p>
<p>Comparing the simple models with this more complex model, we could say that adjusting for <em>largest50</em> does not change much the association between <em>unemployed</em> and violence. Almost the same can be said about the effect of <em>largest50</em> when holding <em>unemployed</em> fixed.</p>
<p>If we look at the <span class="math inline">\(R^2\)</span>, we can see that it is higher than before. This quantity, the R squared, will always increase as a consequence of adding new variables, even if the new variables added are weakly related to the response variable. However, the increase we are observing suggests that adding these two variables results in a substantial improvement to our previous model.</p>
<div class="sourceCode" id="cb469"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb469-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb469-1" tabindex="-1"></a><span class="co"># check the R squared of the multiple regression model</span></span>
<span id="cb469-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb469-2" tabindex="-1"></a><span class="fu">summary</span>(multiple_regression)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.3951664</code></pre>
</div>
<div id="rescaling-input-variables-to-assist-interpretation" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Rescaling input variables to assist interpretation<a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#rescaling-input-variables-to-assist-interpretation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The interpretation of regression coefficients is sensitive to the scale of measurement of the independent variables. This means one cannot compare the magnitude of the coefficients to compare the relevance of variables to predict the response variable. Let’s look at the following multiple regression model, including five independent variables. How can we tell which independent variable have a stronger effect?</p>
<div class="sourceCode" id="cb471"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb471-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb471-1" tabindex="-1"></a><span class="co"># fit new multiple regression model with more independent variables</span></span>
<span id="cb471-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb471-2" tabindex="-1"></a>multiple_regression_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(viol_r <span class="sc">~</span> unemployed <span class="sc">+</span> largest50 <span class="sc">+</span> black <span class="sc">+</span> fborn <span class="sc">+</span> log_incarceraton, <span class="at">data=</span>df)</span>
<span id="cb471-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb471-3" tabindex="-1"></a></span>
<span id="cb471-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb471-4" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb471-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb471-5" tabindex="-1"></a>multiple_regression_2</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = viol_r ~ unemployed + largest50 + black + fborn + 
##     log_incarceraton, data = df)
## 
## Coefficients:
##      (Intercept)        unemployed         largest50             black  
##          221.896            80.555           246.871             9.078  
##            fborn  log_incarceraton  
##           -4.102           -50.506</code></pre>
<p>We just cannot. One way of dealing with this is by rescaling the input variables. A common method involves subtracting the mean and dividing it by the standard deviation of each numerical input. The coefficients in these models are the expected difference in the response variable, comparing units that differ by one standard deviation in the predictor while adjusting for other predictors in the model.</p>
<p>Instead, <a href="http://www.stat.columbia.edu/~gelman/research/published/standardizing7.pdf">Gelman (2008)</a> has proposed dividing each numeric variable <em>by two times its standard deviation</em> so that the generic comparison is with inputs equal to plus/minus one standard deviation. As Gelman explains, the resulting coefficients are comparable to untransformed binary predictors. The implementation of this approach in the <code>arm</code> package subtracts the mean of each binary input while subtracting the mean and dividing it by two standard deviations for every numeric input.</p>
<p>The way we would obtain these rescaled inputs uses the <code>standardize()</code> function of the <code>arm</code> package, which takes the name of the stored fit model as an argument.</p>
<div class="sourceCode" id="cb473"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb473-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb473-1" tabindex="-1"></a><span class="co"># install package you haven&#39;t yet; you only need to do it once</span></span>
<span id="cb473-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb473-2" tabindex="-1"></a><span class="do">## install.packages(&quot;arm&quot;)</span></span>
<span id="cb473-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb473-3" tabindex="-1"></a></span>
<span id="cb473-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb473-4" tabindex="-1"></a><span class="co"># load &#39;arm&#39; package</span></span>
<span id="cb473-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb473-5" tabindex="-1"></a><span class="fu">library</span>(arm)</span>
<span id="cb473-6"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb473-6" tabindex="-1"></a></span>
<span id="cb473-7"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb473-7" tabindex="-1"></a><span class="co"># obtain standardised results</span></span>
<span id="cb473-8"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb473-8" tabindex="-1"></a><span class="fu">standardize</span>(multiple_regression_2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = viol_r ~ z.unemployed + c.largest50 + z.black + 
##     z.fborn + z.log_incarceraton, data = df)
## 
## Coefficients:
##        (Intercept)        z.unemployed         c.largest50             z.black  
##             546.21              270.06              246.87              297.93  
##            z.fborn  z.log_incarceraton  
##             -98.15              -30.72</code></pre>
<p>Notice that the main change affects the numerical predictors. The unstandardised coefficients are influenced by the degree of variability in your predictors, which means they will typically be larger for your binary inputs. With unstandardised coefficients, you are comparing the complete change in one variable (whether one is a large city or not) with one-unit changes in your numerical variable, which may not amount to much change. So, by putting in a comparable scale, you avoid this problem.</p>
<p>Standardising in the way described here will help you to make fairer comparisons. These standardised coefficients are comparable in a way that the unstandardised coefficients are not. We can now see what inputs have a comparatively stronger effect. It is very important to realise, though, that one <strong>should not</strong> compare standardised coefficients <em>across different models</em>.</p>
</div>
<div id="testing-conditional-hypothesis-interactions" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Testing conditional hypothesis: interactions<a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#testing-conditional-hypothesis-interactions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the social sciences, there is a great interest in what are called conditional hypotheses or interactions. Many of our theories do not assume simply <strong>additive effects</strong> but <strong>multiplicative effects</strong>. For example, <a href="http://euc.sagepub.com/content/8/5/401.short">Wikstrom and his colleagues (2011)</a> suggest that the threat of punishment only affects the probability of involvement in crime for those who have a propensity to offend but is largely irrelevant for people who do not have this propensity. Or you may think that a particular crime prevention programme may work in some environments but not in others. The interest in this kind of conditional hypothesis is growing.</p>
<p>One of the assumptions of the regression model is that the relationship between the dependent variable and the independent variables is additive. That is, if you have two independent variables, <code>X1</code> and <code>X2</code>, regression assumes that the effect of <code>X1</code> on <code>Y</code> is the same at all levels of <code>X2</code>. If that is not the case, you are then violating one of the assumptions of regression. This is, in fact, one of the most important assumptions of regression (see previous week for details), even if researchers often overlook it.</p>
<p>One way of extending our model to accommodate for interaction effects is to add additional terms to our model, a third predictor, <code>X3</code>, where <code>X3</code> is simply the product of multiplying <code>X1</code> by <code>X2</code>. Notice that we keep a term for each of the <strong>main effects</strong> (the original predictors) as well as a new term for the interaction effect. “Analysts should include all constitutive terms when specifying multiplicative interaction models except in very rare circumstances” (Brambor et al., 2006: 66). The model now looks like this:</p>
<p><span class="math display">\[
Y = \alpha + \beta_1\cdot X_1 + \beta_2\cdot X_2 + \beta_3\cdot X_1\cdot X_2
\]</span></p>
<p>How do we do this in <code>R</code>? One way is to use the following notation in the formula argument. Notice how we have added a third term, <code>unemployed:largest50</code>, which is asking <code>R</code> to test the conditional hypothesis that the size of the cities may have a different impact on the violent crime rate.</p>
<div class="sourceCode" id="cb475"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb475-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb475-1" tabindex="-1"></a><span class="co"># fit multiple regression model with an interaction term</span></span>
<span id="cb475-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb475-2" tabindex="-1"></a>multiple_regression_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(viol_r <span class="sc">~</span> unemployed <span class="sc">+</span> largest50 <span class="sc">+</span> unemployed<span class="sc">:</span>largest50 , <span class="at">data =</span> df)</span>
<span id="cb475-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb475-3" tabindex="-1"></a></span>
<span id="cb475-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb475-4" tabindex="-1"></a><span class="do">## alternatively, we could also set the same model using the following code:</span></span>
<span id="cb475-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb475-5" tabindex="-1"></a><span class="co"># multiple_regression_3 &lt;- lm(viol_r ~ unemployed * largest50 , data = df)</span></span>
<span id="cb475-6"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb475-6" tabindex="-1"></a></span>
<span id="cb475-7"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb475-7" tabindex="-1"></a><span class="co"># now, print results</span></span>
<span id="cb475-8"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb475-8" tabindex="-1"></a>multiple_regression_3</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = viol_r ~ unemployed + largest50 + unemployed:largest50, 
##     data = df)
## 
## Coefficients:
##          (Intercept)            unemployed             largest50  
##              -157.11                103.65               -121.22  
## unemployed:largest50  
##                64.22</code></pre>
<div class="sourceCode" id="cb477"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb477-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb477-1" tabindex="-1"></a><span class="co"># check the R squared</span></span>
<span id="cb477-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb477-2" tabindex="-1"></a><span class="fu">summary</span>(multiple_regression_3)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.4083445</code></pre>
<p>You see here that, essentially, you have only two independent variables (the size of the city and unemployment) but three slope coefficients. In this case, the test for the interaction effect is very small, which suggests there isn’t such an interaction. The <span class="math inline">\(R^2\)</span> barely changes. Let’s visualise the results with the <code>effects</code> package:</p>
<div class="sourceCode" id="cb479"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb479-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb479-1" tabindex="-1"></a><span class="co"># install package if you haven&#39;t done do</span></span>
<span id="cb479-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb479-2" tabindex="-1"></a><span class="do">## install.packages(&quot;effects&quot;)</span></span>
<span id="cb479-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb479-3" tabindex="-1"></a></span>
<span id="cb479-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb479-4" tabindex="-1"></a><span class="co"># load the &#39;effects&#39; package</span></span>
<span id="cb479-5"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb479-5" tabindex="-1"></a><span class="fu">library</span>(effects)</span></code></pre></div>
<pre><code>## Warning: package &#39;effects&#39; was built under R version 4.3.3</code></pre>
<pre><code>## Loading required package: carData</code></pre>
<pre><code>## lattice theme set by effectsTheme()
## See ?effectsTheme for details.</code></pre>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb483-1" tabindex="-1"></a><span class="co"># plot interaction effects</span></span>
<span id="cb483-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb483-2" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(multiple_regression_3), <span class="at">ask =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p><img src="07_regression_III_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Notice that, essentially, what we are doing is running two regression lines and testing whether the slope is different for the two groups. The intercept is different; we know that the largest cities are more violent, but what we are testing here is whether violence goes up in a steeper fashion (and in the same direction) for one or the other group as unemployment goes up. We see that’s not the case here. The estimated lines are almost parallel…</p>
<p>A word of warning: the moment you introduce an interaction effect, the meaning of the coefficients for the other predictors changes (what it is often referred to as the “main effects” as opposed to the interaction effect). You cannot retain the interpretation we introduced earlier. Now, for example, the coefficient for the <em>largest50</em> variable relates to the marginal effect of this variable when <em>unemployment</em> equals zero. The typical table of results helps you to understand whether the effects are significant but offers little of interest that will help you meaningfully interpret what the effects are. For this, it is better if you use some of the graphical displays we have covered.</p>
<p>Essentially, the regression coefficients that get printed are interpretable only for certain groups. So now:</p>
<ul>
<li><p>The intercept still represents the predicted score of violence for the smaller cities and has a score of 0 in unemployment (as before).</p></li>
<li><p>The coefficient of the <em>largest50Yes</em> predictor now can be thought of as the difference between the predicted score of violence for small cities <em>that have a score of 0 in unemployment</em> and largest cities <em>that have a score of 0 in unemployment</em>.</p></li>
<li><p>The coefficient of <em>unemployed</em> now becomes the comparison of mean violence <em>for small cities</em> that differ by one point in unemployment.</p></li>
<li><p>The coefficient for the interaction term represents the difference in the slope for <em>unemployed</em> comparing smaller and largest cities, the difference in the slope of the two lines that we visualised above.</p></li>
</ul>
<p>Models with interaction terms are too often misinterpreted. We strongly recommend you read this piece by <a href="https://www.cambridge.org/core/journals/political-analysis/article/abs/understanding-interaction-models-improving-empirical-analyses/9BA57B3720A303C61EBEC6DDFA40744B">Brambor et al (2005)</a> to understand some of the issues involved. When discussing logistic regression, we will return to this and will consider tricks to ease the interpretation.</p>
<p>Equally, <a href="https://www.jstatsoft.org/article/view/v008i15">John Fox (2003)</a> piece on the <code>effects</code> package goes into much more detail than we can explain here - the logic and some of the options that are available when producing plots to show interactions with this package. You may also want to look at the newer <code>interactions</code> package <a href="https://interactions.jacob-long.com/index.html">here</a>.</p>
<!--## Plotting residuals

Many of the assumptions can be tested first by having a look at your residuals. Remember, the residuals are the 'error' in your model. In previous weeks, we defined the ordinary residuals as the difference between the observed and the predicted values, the distance between the points in your scatterplot and the regression line. Apart from the ordinary residuals, most software computes other forms of closely related ones: the standardised, the studentised, and the Pearson residuals. 

The raw residuals are just the difference between the observed and the predicted, the other three are ways of normalising this measure, so you can compare what is large, what is small, etc. For example, with the standardized residuals, you essentailly calculate z scores, and given a normal distribution of the standardized residuals, the mean is 0, and the standard deviations is 1. 
Pearson residuas are raw residuals divided by the standard error of the observed value. 
Studentized resiruals (also called standardized pearson residuals) are raw residuals divided by their standard error. 
You can read more about these [here](https://r-forge.r-project.org/scm/viewvc.php/*checkout*/pkg/BinomTools/inst/ResidualsGLM.pdf?revision=6&root=binomtools&pathrev=6). 

Plotting these residuals versus the fitted values and versus each of the predictors is the most basic way of diagnosing problems with your regression model. However, as Fox and Weisberg (2011) emphasise 
> this "is useful for revealing problems but less useful for determining the exact nature of the problem" and consequently one needs "other diagnostic graphs to suggest improvements to the model".

In the previous session we fitted the model `tcviolent ~ tcarea + sex`. This was our `fit_3` model during that session. You may have to run the model again if you do not have it in your global environment.

To obtain the basic residual plots for this model we use the `residualPlots()` function of the `car` package.



```r
library(car)
```

```
## 
## Attaching package: 'car'
```

```
## The following object is masked from 'package:arm':
## 
##     logit
```

```
## The following object is masked from 'package:dplyr':
## 
##     recode
```

```r
BCS0708<-read.csv("https://raw.githubusercontent.com/eonk/dar_book/main/datasets/BCS0708.csv")

fit_3 <- lm(tcviolent ~ tcarea + sex, data=BCS0708)
residualPlots(fit_3)
```

<img src="07_regression_III_files/figure-html/unnamed-chunk-20-1.png" width="672" />

```
##            Test stat Pr(>|Test stat|)    
## tcarea        6.2571        4.123e-10 ***
## sex                                      
## Tukey test    4.6065        4.094e-06 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```
This function will produce plots of the Pearson residuals versus each of the predictors in the model and versus the fitted values.

#### Residuals vs predicted values
The most important of this is the last one, *the scatterplot of the Pearson residuals versus the fitted values*. In these plots one has to pay particular attention to nonlinear trends, trends in variations across the graph, but also isolated points. 
Ideally a plot of the residuals should show that: 

- they’re pretty symmetrically distributed, tending to cluster towards the middle of the plot
- they’re clustered around the lower single digits of the y-axis (e.g., 0.5 or 1.5, not 30 or 150)
- in general there aren’t clear patterns

For example this is a good looking scatterplot of residuals vs fitted values: 

![](imgs/respre.png) 

On the other hand, if your plot isn’t evenly distributed vertically, or they have an outlier, or they have a clear shape to them, that indicates you can detect a clear pattern or trend in your residuals. In this case, then your model has room for improvement.

For example, these are scatterplots of residuals vs fitted values that indicate a problem: 
![](imgs/respre2.png) 
![](imgs/respre3.png) 
![](imgs/respre4.png) 
![](imgs/respre5.png) 

How concerned should you be if your model isn’t perfect, if your residuals look a bit unhealthy? It’s up to you. Most of the time a decent model is better than none at all. So take your model, try to improve it, and then decide whether the accuracy is good enough to be useful for your purposes.

#### Residuals vs predictors

These plots are related to the **homogeneity of variance** assumption we introduced earlier.

When the predictor is **categorical**, we will see a collection of boxplots (one for each level in the predictor). A good fit will be indicated by boxplots that have the same centre and similar spread. 

When the predictor is **numeric**, we see a scatterplot of the predictor against the Pearson residuals. Here we also look at any systematic differences in the spread of the residuals across the X axis. When the variances are not unequal you can often see a funnel form shaping up, with less variance at one end of the X axis than the other. Though other systematic patterns are also possible. You also need to pay attention to the shape of the red line printed in the output. This line should be straight. If you observe non-linearities (e.g., a curved line), this may be a more serious issue than the unequal spread and will need addressing.

#### Diagnostic

When you run the `residualPlots()` function R will also print two numerical tests. 

First we have a curvature test for each of the plots by adding a quadratic term and testing the quadratic to be zero (more on this in a few sections). This is Tukey's test for nonadditivity when plotting against fitted values. When this test is significant it may indicate a **lack of fit** for this particular predictor. 

The Tukey test optimally should not be significant. We can see in the first of the three plots that the red line is a bit curved. It is this pattern that the printed tests are picking up. 


#### Marginal plots
We can further diagnose the model by printing **marginal model plots** using the `marginalModelPlots()` function of the `car` package.


```
## Error in plot.window(...): need finite 'xlim' values
```

<img src="07_regression_III_files/figure-html/unnamed-chunk-21-1.png" width="672" />

This will plot a scatterplot for each predictor variable against the response variable. This displays the conditional distribution of the response given each predictor, *ignoring the other predictors*. They are called marginal plots because they show the marginal relationship between the outcome and *each predictor*. It will also print a scatterplot of the response versus the fitted value displaying the conditional distribution of the outcome given the fit of the model. We observe here the curvature that was already identified by the previous plots (notice the blue line).

We can also use the `marginalModelPlots()` function to assess the **homogeneity of variance** assumption using the following argument:


```r
marginalModelPlots(fit_3, sd = TRUE)
```

```
## Warning in xy.coords(x, y, xlabel, ylabel, log): NAs introduced by coercion
```

```
## Warning in min(x): no non-missing arguments to min; returning Inf
```

```
## Warning in max(x): no non-missing arguments to max; returning -Inf
```

```
## Error in plot.window(...): need finite 'xlim' values
```

<img src="07_regression_III_files/figure-html/unnamed-chunk-22-1.png" width="672" />

This will print the estimated standard deviation lines to the graph. You would want this to be **constant** across the X axis.

#### Diagnostic for homoskedasiticity
And since we are discussing homoskedasiticity (e.g., homogeneity of variance or constant/equal variance), it is worth pointing out that the `car` package implements a score test that evaluates whether the variance is constant. To obtain this test we use the `ncvTest()` function.


```r
ncvTest(fit_3)
```

```
## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 186.8947, Df = 1, p = < 2.22e-16
```

When the test is **significant**, as it is here, we may suspect there **is** a problem with non-constant variance (also called heterokedasticity). In practice, should already be visible from the plot of residuals versus fits plot.
-->
</div>
<div id="multicollinearity" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> Multicollinearity<a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#multicollinearity" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The regression model may experience problems when there is strong collinearity—when the predictors are related to each other. In these scenarios, the standard errors for the coefficients will be large, and the confidence intervals will be broader. Thus, it will be more difficult to detect a significant relationship, even if there is one.</p>
<p>To diagnose multicollinearity, the first step may be to observe the correlation between the predictors in the model. Let’s first subset the data to obtain only the relevant predictors and our main outcome. For this, I will introduce another form of selecting columns in a data frame using the <code>dplyr</code> package. We will be using the Boston data avaible from the MASS package in R - we have used this in previous weeks.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb484-1" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb484-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb484-2" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">quietly=</span><span class="cn">TRUE</span>, <span class="at">warn.conflict=</span><span class="cn">FALSE</span>)</span>
<span id="cb484-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb484-3" tabindex="-1"></a>data <span class="ot">&lt;-</span> Boston</span>
<span id="cb484-4"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb484-4" tabindex="-1"></a>Boston_R <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">select</span>(data, crim, lstat, dis, chas, medv)</span></code></pre></div>
<p>Then, we can obtain the correlations using the <code>cor()</code> function.</p>
<div class="sourceCode" id="cb485"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb485-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb485-1" tabindex="-1"></a>c_1 <span class="ot">&lt;-</span> <span class="fu">cor</span>(Boston_R)</span>
<span id="cb485-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb485-2" tabindex="-1"></a>c_1</span></code></pre></div>
<pre><code>##              crim      lstat         dis        chas       medv
## crim   1.00000000  0.4556215 -0.37967009 -0.05589158 -0.3883046
## lstat  0.45562148  1.0000000 -0.49699583 -0.05392930 -0.7376627
## dis   -0.37967009 -0.4969958  1.00000000 -0.09917578  0.2499287
## chas  -0.05589158 -0.0539293 -0.09917578  1.00000000  0.1752602
## medv  -0.38830461 -0.7376627  0.24992873  0.17526018  1.0000000</code></pre>
<p>And then, we can visualise these correlations with the <code>corrplot</code> package.</p>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb487-1" tabindex="-1"></a><span class="fu">library</span>(corrplot, <span class="at">quietly =</span> <span class="cn">TRUE</span>, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## corrplot 0.92 loaded</code></pre>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb489-1" tabindex="-1"></a><span class="fu">corrplot</span>(c_1, <span class="at">order =</span> <span class="st">&quot;hclust&quot;</span>, <span class="at">tl.pos=</span><span class="st">&quot;d&quot;</span>)</span></code></pre></div>
<p><img src="07_regression_III_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>We can see some non-trivial correlations between some of the predictors, particularly between median property value and per cent lower status (r=-73).</p>
<p>Correlations among pairs of variables will only give you a first impression of the problem. What we are really concerned about is what happens once you throw all the variables in the model. Not all problems with multicollinearity will be detected by the correlation matrix. The recommended reading describes the variance inflation factor as a tool to diagnose multicollinearity. Let’s look at the one we obtain with the first model (pre-transformations) that we run with the <code>Boston</code> dataset:</p>
<div class="sourceCode" id="cb490"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb490-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb490-1" tabindex="-1"></a><span class="fu">library</span>(car)<span class="co"># make sure you install the package if not available</span></span>
<span id="cb490-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb490-2" tabindex="-1"></a>fit_B1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(crim <span class="sc">~</span> medv <span class="sc">+</span> lstat <span class="sc">+</span> dis <span class="sc">+</span> chas, <span class="at">data =</span> Boston)</span>
<span id="cb490-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb490-3" tabindex="-1"></a><span class="fu">vif</span>(fit_B1)</span></code></pre></div>
<pre><code>##     medv    lstat      dis     chas 
## 2.358517 2.850675 1.399747 1.057865</code></pre>
<p>Typically, a VIF larger than 5 or 10 indicates serious problems with collinearity. Fox (2008) recommends using the square root of the variance inflation factor:</p>
<div class="sourceCode" id="cb492"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb492-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb492-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">vif</span>(fit_B1))</span></code></pre></div>
<pre><code>##     medv    lstat      dis     chas 
## 1.535746 1.688394 1.183109 1.028525</code></pre>
<p>Typically, it is assumed that you need a value greater than 2 for the square root of the variance inflation factor before collinearity seriously impairs the precision of the estimation. It does not look as if we would have to worry much on the basis of these results.</p>
<p>When you have a set of related inputs or regressors (either because you have a multicategory factor and various dummy variables or because you have polynomial regressors), you cannot use the variance inflation factor. There is, however, a similar statistic that you can use in these contexts: the <strong>generalised variance inflation factor</strong>. We could use this measure for our final model for the <code>Boston</code> data. We invoke this statistic using the same code as before:</p>
<div class="sourceCode" id="cb494"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb494-1"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb494-1" tabindex="-1"></a>fit_B3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(crim) <span class="sc">~</span> <span class="fu">poly</span>(medv, <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">log</span>(lstat) <span class="sc">+</span> <span class="fu">log</span>(dis) <span class="sc">+</span> chas, <span class="at">data =</span> Boston)</span>
<span id="cb494-2"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb494-2" tabindex="-1"></a></span>
<span id="cb494-3"><a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#cb494-3" tabindex="-1"></a><span class="fu">vif</span>(fit_B3)</span></code></pre></div>
<pre><code>##                   GVIF Df GVIF^(1/(2*Df))
## poly(medv, 2) 4.439803  2        1.451580
## log(lstat)    4.151409  1        2.037501
## log(dis)      1.770096  1        1.330450
## chas          1.058015  1        1.028599</code></pre>
<p>Now that we are using the transformed variables, it looks as if we have more of an issue with the coefficient for <code>lstat</code>. The confidence interval for this coefficient is about 2 times larger than it would be without collinearity, which goes a long way towards explaining why it is no longer significant.</p>
<p>The problem with collinear inputs is that they do not add much new to the model. Non-collinearity is not an assumption of the regression model. And everything is related to everything else, to some extent, at least. But if a predictor is strongly related to some other input, then we are simply adding redundant information to the model. If you are developing a risk assessment tool for probation, you don’t want to add loads of predictors that are highly correlated (for this simply requires probation to collect redundant information). Also, in these situations is hard to tell apart the relative importance of the collinear predictors (if you are interested in explanation rather than prediction). It can be difficult to separate their effects.</p>
<p>A number of solutions to multicollinearity have been proposed, from dropping the culprits to creating composite variables that summarise variation among the correlated inputs to more complex techniques. Still, all these are well beyond the aims of this course.</p>
<p>It is very important, however, to remember that there are some circumstances in which multicollinearity can be safely ignored. Professor Paul Allison <a href="http://www.statisticalhorizons.com/multicollinearity">discusses this issue</a> in his blog, and you may want to check the full discussion. Essentially, Prof. Allison argues that one can ignore multicollinearity when:</p>
<ul>
<li><p>“The variables with high VIFs are control variables, and the variables of interest do not have high VIFs… In this case, the coefficients of the variables of interest are not affected, and the performance of the control variables as controls is not impaired.”</p></li>
<li><p>“The high VIFs are caused by the inclusion of powers or products of other variables. If you specify a regression model with both x and x2, there’s a good chance that those two variables will be highly correlated. Similarly, if your model has x, z, and xz, both x and z are likely to be highly correlated with their product. This is not something to be concerned about, however, because the p-value for xz is not affected by the multicollinearity…”</p></li>
<li><p>“The variables with high VIFs are indicator (dummy) variables that represent a categorical variable with three or more categories. If the proportion of cases in the reference category is small, the indicator variables will necessarily have high VIFs, even if the categorical variable is not associated with other variables in the regression model.”</p></li>
</ul>
<!--## Summary: exercise for this week
Once you finish your lab session, don't forget to do this [Exercise](https://eonk.shinyapps.io/MCD_ex) and have a chance to sum-up this week's R codes.-->

</div>
</div>
<div class="footnotes">
<hr />
<ol start="9">
<li id="fn9"><p>We recommend reading chapter 13 “Woes of regression coefficients” of an old book Mostseller and Tukey (1977) Data Analysis and Regression. Reading: Addison-Wesley Publishing.<a href="regression-iii-categorical-independent-variables-and-multiple-regression-models.html#fnref9" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regression-ii-numerical-independent-variables.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="categorical-variables-and-logistic-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
